variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: ubuntu:latest
  before_script:
    - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    - export TZ=Europe/Zurich
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    - apt-get -y update && apt-get -y upgrade
    - apt-get -y install gcc-8 cmake 
    - apt-get -y install libsdl2-dev libsdl2-image-dev libsdl2-net-dev libsdl2-ttf-dev libsdl2-mixer-dev

stages:
  - configure
  - build
  - test

configure:
  stage: configure
  script: cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug
  artifacts:
    paths:
      - ./build

build:
  stage: build
  script: cmake --build build
  artifacts:
    paths:
      - ./build

test_cmocka:
  stage: test
  script: |
    cd ./build
    export CMOCKA_MESSAGE_OUTPUT=xml
    export CMOCKA_XML_FILE=cmocka_junit.xml
    export SDL_VIDEODRIVER=dummy
    ctest --verbose --timeout 10
  artifacts:
    when: always
    reports:
      junit: ./build/cmocka_junit.xml

test_cppcheck:
  stage: test
  script: |
    apt-get -y install cppcheck python3 python3-pip
    pip3 install cppcheck-junit
    cppcheck --project=./build/compile_commands.json --enable=all --inconclusive \
      --suppress=unusedFunction --suppress=missingIncludeSystem --suppress=unmatchedSuppression --inline-suppr
    cppcheck --project=./build/compile_commands.json --enable=all --inconclusive --suppress=unusedFunction \
      --suppress=missingIncludeSystem --suppress=unmatchedSuppression --inline-suppr --xml-version=2 2> cppcheck_result.xml
    cppcheck_junit cppcheck_result.xml cppcheck_junit.xml
  artifacts:
    when: always
    reports:
      junit: ./cppcheck_junit.xml
